In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

In [6]:
df= pd.read_csv("E:/Life Expectancy Data.csv")

In [246]:
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [7]:

df=df.drop_duplicates()
df=df.dropna()

In [8]:
df1=df.iloc[:,16:]

In [9]:
df1 = df1.drop(["Population"],axis=1)

In [11]:
df1.describe()

,GDP,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
count,1649.000000,1649.000000,1649.000000,1649.000000,1649.000000
mean,5566.031887,4.850637,4.907762,0.631551,12.119891
std,11475.900117,4.599228,4.653757,0.183089,2.795388
min,1.681350,0.100000,0.100000,0.000000,4.200000
25%,462.149650,1.600000,1.700000,0.509000,10.300000
50%,1592.572182,3.000000,3.200000,0.673000,12.300000
75%,4718.512910,7.100000,7.100000,0.751000,14.000000
max,119172.741800,27.200000,28.200000,0.936000,20.700000

In [12]:
x = df1
y=df.iloc[:,3]

In [13]:
x

,GDP,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,584.259210,17.2,17.3,0.479,10.1
1,612.696514,17.5,17.5,0.476,10.0
2,631.744976,17.7,17.7,0.470,9.9
3,669.959000,17.9,18.0,0.463,9.8
4,63.537231,18.2,18.2,0.454,9.5
5,553.328940,18.4,18.4,0.448,9.2
6,445.893298,18.6,18.7,0.434,8.9
7,373.361116,18.8,18.9,0.433,8.7
8,369.835796,19.0,19.1,0.415,8.4
9,272.563770,19.2,19.3,0.405,8.1
10,25.294130,19.3,19.5,0.396,7.9
11,219.141353,19.5,19.7,0.381,6.8
12,198.728544,19.7,19.9,0.373,6.5
13,187.845950,19.9,2.2,0.341,6.2
14,117.496980,2.1,2.4,0.340,5.9
15,114.560000,2.3,2.5,0.338,5.5
16,3954.227830,1.2,1.3,0.762,14.2
17,4575.763787,1.2,1.3,0.761,14.2
18,4414.723140,1.3,1.4,0.759,14.2
19,4247.614380,1.3,1.4,0.752,14.2
20,4437.178680,1.4,1.5,0.738,13.3
21,494.358832,1.4,1.5,0.725,12.5
22,4114.136545,1.5,1.6,0.721,12.2
23,437.539647,1.6,1.6,0.713,12.0
24,363.136850,1.6,1.7,0.703,11.6
25,35.129300,1.7,1.8,0.696,11.4
26,279.142931,1.8,1.8,0.685,10.8
27,2416.588235,1.8,1.9,0.681,10.9
28,189.681557,1.9,2.0,0.674,10.7
29,1453.642777,2.0,2.1,0.670,10.7
...,...,...,...,...,...
2853,1787.947230,1.6,1.5,0.000,10.7
2854,158.527240,1.6,1.6,0.000,10.4
2855,1353.934819,1.7,1.6,0.000,10.2
2856,1362.617310,1.7,1.6,0.000,10.1
2857,1469.849149,1.7,1.7,0.000,9.6
2907,1738.882200,6.3,6.2,0.570,12.5
2908,185.793359,6.4,6.2,0.565,12.5
2909,1734.936120,6.5,6.3,0.554,12.3
2910,1644.619672,6.6,6.4,0.543,12.0
2911,1463.213573,6.7,6.5,0.533,11.8
2912,1139.112330,6.7,6.6,0.518,11.6
2913,1369.682490,6.8,6.7,0.504,11.4
2914,114.587985,6.9,6.8,0.492,11.1
2915,13.154199,7.0,6.9,0.479,10.9
2916,691.317816,7.1,7.0,0.467,10.7
2923,127.474620,5.9,5.7,0.498,10.3
2924,111.227396,6.2,6.0,0.488,10.4
2925,955.648466,6.5,6.4,0.464,9.8
2926,839.927936,6.8,6.7,0.452,10.1
2927,713.635620,7.1,7.0,0.436,10.0
2928,65.824121,7.5,7.4,0.419,9.9
2929,325.678573,7.8,7.8,0.421,9.7
2930,396.998217,8.2,8.2,0.414,9.6
2931,414.796232,8.6,8.6,0.408,9.5
2932,444.765750,9.0,9.0,0.406,9.3
2933,454.366654,9.4,9.4,0.407,9.2
2934,453.351155,9.8,9.9,0.418,9.5
2935,57.348340,1.2,1.3,0.427,10.0
2936,548.587312,1.6,1.7,0.427,9.8
2937,547.358879,11.0,11.2,0.434,9.8

In [14]:
y

0       65.0
1       59.9
2       59.9
3       59.5
4       59.2
5       58.8
6       58.6
7       58.1
8       57.5
9       57.3
10      57.3
11      57.0
12      56.7
13      56.2
14      55.3
15      54.8
16      77.8
17      77.5
18      77.2
19      76.9
20      76.6
21      76.2
22      76.1
23      75.3
24      75.9
25      74.2
26      73.5
27      73.0
28      72.8
29      73.3
        ...
2853    69.6
2854    69.4
2855    69.3
2856    69.1
2857    69.0
2907    61.1
2908    63.0
2909    59.2
2910    58.2
2911    58.0
2912    57.4
2913    55.7
2914    52.6
2915    58.0
2916    49.3
2923    59.2
2924    58.0
2925    56.6
2926    54.9
2927    52.4
2928    50.0
2929    48.2
2930    46.6
2931    45.4
2932    44.6
2933    44.3
2934    44.5
2935    44.8
2936    45.3
2937    46.0
Name: Life expectancy , Length: 1649, dtype: float64

In [15]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [16]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [17]:
y_predict = model.predict(x_test)

In [18]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test,y_predict)
mse

34.13349502064162

In [19]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test,y_predict)
r2

0.5685768027949858

In [20]:
from sklearn.metrics import mean_absolute_error
mas = mean_absolute_error(y_test,y_predict)
mas

4.315244379802925